/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package utility;

import dhananistockmanagement.DeskFrame;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import support.Constants;
import support.Library;

/**
 *
 * @author @JD@
 */
public class ChangePassword extends javax.swing.JInternalFrame {
    Library lb = new Library();
    String Syspath = System.getProperty("user.dir");

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        lb.registerShortKeys(getRootPane(), jbtnClose, new JButton(""), new JButton(""), new JButton(""));
        setIconToPnael();
        setPermission();
        setTitle(Constants.CHANGE_PASSWORD_FORM_NAME);
    }

    private void setPermission() {
        lb.setUserRightsToButton(jbtnChangePwd, Constants.CHANGE_PASSWORD_FORM_ID, "EDIT");
    }

    private void setIconToPnael() {
        Syspath += File.separator + "Resources" + File.separator + "Images" + File.separator;
        jbtnChangePwd.setIcon(new ImageIcon(Syspath +"chngPwd.png"));
        jbtnClose.setIcon(new ImageIcon(Syspath +"close.png"));
    }

    @Override
    public void dispose() {
        try {
            DeskFrame.removeFromScreen(DeskFrame.tabbedPane.getSelectedIndex());
            super.dispose();
        } catch (Exception ex) {
            lb.printToLogFile("Exception at dispose In Change Password", ex);
        }
    }

    private void jbtnChangePwdActionPerformedRoutine() {
        if (jtxtNewPwd.getText().trim().equalsIgnoreCase(jtxtConfirmPwd.getText().trim())) {
            if (lb.changePwd(DeskFrame.user_id, jtxtNewPwd.getText())) {
                JOptionPane.showMessageDialog(this, "password changed sucessfully", Constants.CHANGE_PASSWORD_FORM_NAME, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "password changed unsucessfull", Constants.CHANGE_PASSWORD_FORM_NAME, JOptionPane.ERROR_MESSAGE);
                jtxtNewPwd.requestFocusInWindow();
            }
        } else {
            JOptionPane.showMessageDialog(this, "new password and confirm password are not match.", Constants.CHANGE_PASSWORD_FORM_NAME, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void close() {
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtNewPwd = new javax.swing.JPasswordField();
        jtxtConfirmPwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtOldPwd = new javax.swing.JPasswordField();
        jbtnClose = new javax.swing.JButton();
        jbtnChangePwd = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(253, 243, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(235, 35, 35)), "Change Password", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 2, 16), new java.awt.Color(0, 0, 255))); // NOI18N

        jtxtNewPwd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtNewPwd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jtxtNewPwd.setMinimumSize(new java.awt.Dimension(6, 25));
        jtxtNewPwd.setPreferredSize(new java.awt.Dimension(6, 25));
        jtxtNewPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNewPwdKeyPressed(evt);
            }
        });

        jtxtConfirmPwd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtConfirmPwd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jtxtConfirmPwd.setMinimumSize(new java.awt.Dimension(6, 25));
        jtxtConfirmPwd.setPreferredSize(new java.awt.Dimension(6, 25));
        jtxtConfirmPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtConfirmPwdKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Current Password");
        jLabel1.setMaximumSize(new java.awt.Dimension(86, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(86, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(86, 25));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("New Password");
        jLabel2.setMaximumSize(new java.awt.Dimension(70, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(70, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 25));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Confirm Password");
        jLabel3.setMaximumSize(new java.awt.Dimension(86, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(86, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(86, 25));

        jtxtOldPwd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtOldPwd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jtxtOldPwd.setMinimumSize(new java.awt.Dimension(2, 25));
        jtxtOldPwd.setPreferredSize(new java.awt.Dimension(2, 25));
        jtxtOldPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtOldPwdFocusLost(evt);
            }
        });
        jtxtOldPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtOldPwdKeyPressed(evt);
            }
        });

        jbtnClose.setBackground(new java.awt.Color(204, 255, 204));
        jbtnClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnClose.setForeground(new java.awt.Color(235, 35, 35));
        jbtnClose.setMnemonic('C');
        jbtnClose.setText("CLOSE");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jbtnChangePwd.setBackground(new java.awt.Color(204, 255, 204));
        jbtnChangePwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnChangePwd.setForeground(new java.awt.Color(235, 35, 35));
        jbtnChangePwd.setMnemonic('H');
        jbtnChangePwd.setText("CHANGE");
        jbtnChangePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangePwdActionPerformed(evt);
            }
        });
        jbtnChangePwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnChangePwdKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtNewPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtOldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jbtnChangePwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(246, 246, 246))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnChangePwd, jbtnClose});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtConfirmPwd, jtxtNewPwd, jtxtOldPwd});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtOldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnClose)
                    .addComponent(jbtnChangePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtConfirmPwd, jtxtNewPwd, jtxtOldPwd});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnChangePwd, jbtnClose});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
    close();
}//GEN-LAST:event_jbtnCloseActionPerformed

private void jtxtOldPwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtOldPwdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtNewPwd.requestFocusInWindow();
    }
}//GEN-LAST:event_jtxtOldPwdKeyPressed

private void jtxtNewPwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNewPwdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtConfirmPwd.requestFocusInWindow();
    }
}//GEN-LAST:event_jtxtNewPwdKeyPressed

private void jtxtConfirmPwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtConfirmPwdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jbtnChangePwd.requestFocusInWindow();
    }
}//GEN-LAST:event_jtxtConfirmPwdKeyPressed

private void jbtnChangePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangePwdActionPerformed
    jbtnChangePwdActionPerformedRoutine();
}//GEN-LAST:event_jbtnChangePwdActionPerformed

private void jbtnChangePwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnChangePwdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jbtnChangePwdActionPerformedRoutine();
    }
}//GEN-LAST:event_jbtnChangePwdKeyPressed

    private void jtxtOldPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtOldPwdFocusLost
        if (lb.checkOldPwd(DeskFrame.user_id, jtxtOldPwd.getText())) {
            jtxtNewPwd.requestFocusInWindow();
        } else {
            JOptionPane.showMessageDialog(this, "current password is not valid", Constants.CHANGE_PASSWORD_FORM_NAME, JOptionPane.ERROR_MESSAGE);
            jtxtOldPwd.requestFocusInWindow();
        }
    }//GEN-LAST:event_jtxtOldPwdFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnChangePwd;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JPasswordField jtxtConfirmPwd;
    private javax.swing.JPasswordField jtxtNewPwd;
    private javax.swing.JPasswordField jtxtOldPwd;
    // End of variables declaration//GEN-END:variables
}