/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package utility;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import dhananistockmanagement.DeskFrame;
import support.Constants;
import support.Library;

/**
 *
 * @author @JD@
 */
public class ChangeThemes extends javax.swing.JInternalFrame {
    private static Connection dataConnection = DeskFrame.connMpMain;
    private static Library lb = new Library();
    String Syspath = System.getProperty("user.dir");
    private String theme_id = DeskFrame.theme_cd;

    /**
     * Creates new form ChangeThemes
     */
    public ChangeThemes() {
        initComponents();
        lb.registerShortKeys(getRootPane(), jbtnClose, new JButton(""), new JButton(""), new JButton(""));
        setPermission();
        setIconToPnael();
        setData();
        setTitle(Constants.CHANGE_THEMES_FORM_NAME);
    }

    private void setIconToPnael() {
        Syspath += File.separator + "Resources" + File.separator + "Images" + File.separator;
        jbtnOk.setIcon(new ImageIcon(Syspath +"ok.png"));
        jbtnClose.setIcon(new ImageIcon(Syspath +"Close.png"));
    }

    private void setPermission(){
        lb.setUserRightsToButton(jbtnOk, Constants.CHANGE_THEMES_FORM_ID, "EDIT");
    }

    private void setData() {
        PreparedStatement psLocal = null;
        ResultSet rsLocal = null;
        try {
            psLocal = dataConnection.prepareStatement("SELECT * FROM change_themes");
            rsLocal = psLocal.executeQuery();
            while(rsLocal.next()) {
                final String id = rsLocal.getString("id");
                final JRadioButton button1 = new JRadioButton(rsLocal.getString("theme_name"));
                jPanel1.add(button1);
                jPanel1.setLayout(new GridLayout(10, 1));
                buttonGroup1.add(button1);

                if(DeskFrame.theme_cd.equalsIgnoreCase(id)) {
                    button1.setSelected(true);
                }

                button1.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        theme_id = id;
                    }
                });
            }
        } catch(Exception ex) {
            lb.printToLogFile("Exception at setData in Change Themes", ex);
        }
    }

    private void saveData() {
        PreparedStatement psLocal = null;
        try {
            psLocal = dataConnection.prepareStatement("UPDATE appconfig SET theme_cd = ?");
            psLocal.setString(1, theme_id); // Theme CD
            psLocal.executeUpdate();
            DeskFrame.theme_cd = theme_id;
            JOptionPane.showMessageDialog(this, "Please restart application.", Constants.CHANGE_THEMES_FORM_NAME, JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "Error in save data.", Constants.CHANGE_THEMES_FORM_NAME, JOptionPane.INFORMATION_MESSAGE);
            lb.printToLogFile("Exception at saveData in Change Themes", ex);
        }
    }

    @Override
    public void dispose() {
        try {
            DeskFrame.removeFromScreen(DeskFrame.tabbedPane.getSelectedIndex());
            super.dispose();
        } catch (Exception ex) {
            lb.printToLogFile("Exception at dispose In Change Themes", ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jbtnOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbtnClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(211, 226, 245));

        jbtnOk.setBackground(new java.awt.Color(204, 255, 204));
        jbtnOk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnOk.setForeground(new java.awt.Color(235, 35, 35));
        jbtnOk.setMnemonic('O');
        jbtnOk.setText("CHANGE THEME");
        jbtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkActionPerformed(evt);
            }
        });
        jbtnOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbtnOkKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jbtnClose.setBackground(new java.awt.Color(204, 255, 204));
        jbtnClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnClose.setMnemonic('C');
        jbtnClose.setText("CLOSE");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 493, Short.MAX_VALUE)
                        .addComponent(jbtnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnClose, jbtnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkActionPerformed
        saveData();
        this.dispose();
    }//GEN-LAST:event_jbtnOkActionPerformed

    private void jbtnOkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnOkKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
            jbtnOk.doClick();
        }
    }//GEN-LAST:event_jbtnOkKeyReleased

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnOk;
    // End of variables declaration//GEN-END:variables
}