/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package utility;

import dhananistockmanagement.DeskFrame;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import support.Constants;
import support.Library;

/**
 *
 * @author @JD@
 */
public class ManageEmail extends javax.swing.JInternalFrame {
    Library lb = new Library();
    String Syspath = System.getProperty("user.dir");

    /**
     * Creates new form ManageEmail
     */
    public ManageEmail() {
        initComponents();
        lb.registerShortKeys(getRootPane(), jbtnClose, new JButton(""), new JButton(""), new JButton(""));
        setPermission();
        setIconToPnael();
        setData();
        jtxtEmail.requestFocusInWindow();
        setTitle(Constants.MANAGE_EMAIL_FORM_NAME);
    }

    private void setPermission() {
        lb.setUserRightsToButton(jbtnChangeEmail, Constants.MANAGE_EMAIL_FORM_ID, "EDIT");
    }

    private void setData() {
        String sql = "SELECT * FROM manage_email";
        PreparedStatement psLocal = null;
        ResultSet rsLocal = null;
        try {
            psLocal = DeskFrame.connMpAdmin.prepareStatement(sql);
            rsLocal = psLocal.executeQuery();
            if(rsLocal.next()) {
                jtxtEmail.setText(rsLocal.getString("manage_email"));
                jtxtEmailPwd.setText(rsLocal.getString("manage_pwd"));
                jtxtConfirmPwd.setText(rsLocal.getString("manage_pwd"));
                jtxtPort.setText(rsLocal.getString("manage_port"));
                jtxtHostName.setText(rsLocal.getString("manage_host"));
                jtxtMobileNo.setText(rsLocal.getString("manage_mobno"));
            }
        } catch(Exception ex) {
            lb.printToLogFile("Exception at setData In Manage Email", ex);
        }
    }

    private void setIconToPnael() {
        Syspath += File.separator + "Resources" + File.separator + "Images" + File.separator;
        jbtnChangeEmail.setIcon(new ImageIcon(Syspath +"chngPwd.png"));
        jbtnClose.setIcon(new ImageIcon(Syspath +"close.png"));
    }

    @Override
    public void dispose() {
        try {
            DeskFrame.removeFromScreen(DeskFrame.tabbedPane.getSelectedIndex());
            super.dispose();
        } catch (Exception ex) {
            lb.printToLogFile("Exception at disponse In Manage Email", ex);
        }
    }

    private void close() {
        this.dispose();
    }

    public boolean changeEmail() {
        boolean flag = false;
        try {
            String sql = "UPDATE manage_email SET manage_email = ?, manage_pwd = ?, manage_port = ?, manage_host = ?, manage_mobno = ? WHERE manage_id = 1";
            PreparedStatement pstLocal = DeskFrame.connMpAdmin.prepareStatement(sql);
            pstLocal.setString(1, jtxtEmail.getText()); // Email
            pstLocal.setString(2, jtxtEmailPwd.getText()); // Password
            pstLocal.setString(3, jtxtPort.getText()); // Port
            pstLocal.setString(4, jtxtHostName.getText()); // Host Name
            pstLocal.setString(5, jtxtMobileNo.getText()); // Mobile No
            if (pstLocal.executeUpdate() > 0) {
                flag = true;
            }
        } catch (Exception ex) {
            lb.printToLogFile("exception at changeEmail In Manage Email", ex);
        }
        return flag;
    }

    private void jbtnChangeEmailActionPerformedRoutine() {
        if (jtxtEmailPwd.getText().trim().equalsIgnoreCase(jtxtConfirmPwd.getText().trim())) {
            if (changeEmail()) {
                JOptionPane.showMessageDialog(this, "Email changed sucessfully", Constants.MANAGE_EMAIL_FORM_NAME, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Email changed unsucessfull", Constants.MANAGE_EMAIL_FORM_NAME, JOptionPane.ERROR_MESSAGE);
                jtxtEmailPwd.requestFocusInWindow();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Email password and confirm password are not match.", Constants.MANAGE_EMAIL_FORM_NAME, JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtEmailPwd = new javax.swing.JPasswordField();
        jtxtConfirmPwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnClose = new javax.swing.JButton();
        jbtnChangeEmail = new javax.swing.JButton();
        jtxtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPort = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtHostName = new javax.swing.JTextField();
        jtxtMobileNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(253, 243, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(235, 35, 35)), "Manage Email", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 2, 16), new java.awt.Color(0, 0, 255))); // NOI18N

        jtxtEmailPwd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtEmailPwd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 110, 152)));
        jtxtEmailPwd.setMinimumSize(new java.awt.Dimension(2, 25));
        jtxtEmailPwd.setPreferredSize(new java.awt.Dimension(2, 25));
        jtxtEmailPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtEmailPwdKeyPressed(evt);
            }
        });

        jtxtConfirmPwd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtConfirmPwd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 110, 152)));
        jtxtConfirmPwd.setMinimumSize(new java.awt.Dimension(2, 25));
        jtxtConfirmPwd.setPreferredSize(new java.awt.Dimension(2, 25));
        jtxtConfirmPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtConfirmPwdFocusGained(evt);
            }
        });
        jtxtConfirmPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtConfirmPwdKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Email : ");
        jLabel1.setMaximumSize(new java.awt.Dimension(34, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(34, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 25));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Email Password : ");
        jLabel2.setMaximumSize(new java.awt.Dimension(83, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(83, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(83, 25));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Confirm Password : ");
        jLabel3.setMaximumSize(new java.awt.Dimension(96, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(96, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(96, 25));

        jbtnClose.setBackground(new java.awt.Color(204, 255, 204));
        jbtnClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnClose.setForeground(new java.awt.Color(235, 35, 35));
        jbtnClose.setMnemonic('C');
        jbtnClose.setText("CLOSE");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jbtnChangeEmail.setBackground(new java.awt.Color(204, 255, 204));
        jbtnChangeEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnChangeEmail.setForeground(new java.awt.Color(235, 35, 35));
        jbtnChangeEmail.setMnemonic('H');
        jbtnChangeEmail.setText("CHANGE");
        jbtnChangeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeEmailActionPerformed(evt);
            }
        });
        jbtnChangeEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnChangeEmailKeyPressed(evt);
            }
        });

        jtxtEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 110, 152)));
        jtxtEmail.setMinimumSize(new java.awt.Dimension(2, 25));
        jtxtEmail.setPreferredSize(new java.awt.Dimension(2, 25));
        jtxtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtEmailFocusGained(evt);
            }
        });
        jtxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtEmailKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Port : ");
        jLabel4.setMaximumSize(new java.awt.Dimension(30, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(30, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(30, 25));

        jtxtPort.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtPort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 110, 152)));
        jtxtPort.setMinimumSize(new java.awt.Dimension(2, 25));
        jtxtPort.setPreferredSize(new java.awt.Dimension(2, 25));
        jtxtPort.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPortFocusGained(evt);
            }
        });
        jtxtPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPortKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPortKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Host Name : ");
        jLabel5.setMaximumSize(new java.awt.Dimension(30, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(30, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(30, 25));

        jtxtHostName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtHostName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 110, 152)));
        jtxtHostName.setMinimumSize(new java.awt.Dimension(2, 25));
        jtxtHostName.setPreferredSize(new java.awt.Dimension(2, 25));

        jtxtMobileNo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtMobileNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 110, 152)));
        jtxtMobileNo.setMinimumSize(new java.awt.Dimension(2, 25));
        jtxtMobileNo.setPreferredSize(new java.awt.Dimension(2, 25));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mobile No : ");
        jLabel6.setMaximumSize(new java.awt.Dimension(30, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(30, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(30, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jbtnChangeEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEmailPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtHostName, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnChangeEmail, jbtnClose});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtConfirmPwd, jtxtEmail, jtxtEmailPwd});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmailPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtHostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnChangeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnClose))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtConfirmPwd, jtxtEmail, jtxtEmailPwd});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jtxtPort});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnChangeEmail, jbtnClose});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
    close();
}//GEN-LAST:event_jbtnCloseActionPerformed

private void jtxtEmailPwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmailPwdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtConfirmPwd.requestFocusInWindow();
    }
}//GEN-LAST:event_jtxtEmailPwdKeyPressed

private void jtxtConfirmPwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtConfirmPwdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtPort.requestFocusInWindow();
    }
}//GEN-LAST:event_jtxtConfirmPwdKeyPressed

private void jbtnChangeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeEmailActionPerformed
    jbtnChangeEmailActionPerformedRoutine();
}//GEN-LAST:event_jbtnChangeEmailActionPerformed

private void jbtnChangeEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnChangeEmailKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jbtnChangeEmailActionPerformedRoutine();
    }
}//GEN-LAST:event_jbtnChangeEmailKeyPressed

    private void jtxtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtEmailFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtEmailFocusGained

    private void jtxtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmailKeyPressed
        lb.enterEvent(evt, jtxtEmailPwd);
    }//GEN-LAST:event_jtxtEmailKeyPressed

    private void jtxtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmailKeyTyped
        lb.fixLength(evt, 70);
    }//GEN-LAST:event_jtxtEmailKeyTyped

    private void jtxtPortFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPortFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtPortFocusGained

    private void jtxtPortKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPortKeyPressed
        lb.enterEvent(evt, jbtnChangeEmail);
    }//GEN-LAST:event_jtxtPortKeyPressed

    private void jtxtPortKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPortKeyTyped
        lb.onlyInteger(evt, 4);
    }//GEN-LAST:event_jtxtPortKeyTyped

    private void jtxtConfirmPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtConfirmPwdFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtConfirmPwdFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnChangeEmail;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JPasswordField jtxtConfirmPwd;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JPasswordField jtxtEmailPwd;
    private javax.swing.JTextField jtxtHostName;
    private javax.swing.JTextField jtxtMobileNo;
    private javax.swing.JTextField jtxtPort;
    // End of variables declaration//GEN-END:variables
}