/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package support;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.PreparedStatement;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import dhananistockmanagement.DeskFrame;

/**
 *
 * @author @JD@
 */
public class EmailSelect extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private Library lb = new Library();
    private PickList emailPickList = null;
    String ref_no = "";
    String mode = "";
    int md = 1;
    String Syspath = System.getProperty("user.dir");
    /**
     * Creates new form EmailSelect
     */
    public EmailSelect(java.awt.Frame parent, boolean modal, String ref_no, String mode, int md) {
        super(parent, modal);
        setTitle("Email Select");
        initComponents();
        this.mode = mode;
        this.md = md;
        this.ref_no = ref_no;
        setPickListView();
        setIconToPanel();
        jtxtEmailID.setText(lb.getAccountName(0.00, "EMAIL1", mode, ref_no));

        // Close the dialog when Esc is pressed
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(screenSize.width / 2 - this.getWidth() / 2, screenSize.height / 2 - this.getHeight() / 2, this.getWidth(), this.getHeight());
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    private void setPickListView() {
        emailPickList = new PickList(DeskFrame.connMpAdmin);

        emailPickList.setLayer(getLayeredPane());
        emailPickList.setPickListComponent(jtxtEmailID);
        emailPickList.setNextComponent(jbtnOK);
    }

    private void setIconToPanel() {
        Syspath += File.separator + "Resources" + File.separator + "Images" + File.separator;
        jbtnOK.setIcon(new ImageIcon(Syspath + "E-mail.png"));
        jbtnCancel.setIcon(new ImageIcon(Syspath+"close.png"));
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnOK = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jtxtEmailID = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(253, 243, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(235, 35, 35)), "Email ID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 2, 16), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 35, 35));
        jLabel1.setText("Email ID : ");

        jbtnOK.setBackground(new java.awt.Color(204, 255, 204));
        jbtnOK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnOK.setForeground(new java.awt.Color(235, 35, 35));
        jbtnOK.setMnemonic('O');
        jbtnOK.setText("OK");
        jbtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOKActionPerformed(evt);
            }
        });

        jbtnCancel.setBackground(new java.awt.Color(204, 255, 204));
        jbtnCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnCancel.setForeground(new java.awt.Color(235, 35, 35));
        jbtnCancel.setMnemonic('C');
        jbtnCancel.setText("CLOSE");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jtxtEmailID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtxtEmailID.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(235, 35, 35)));
        jtxtEmailID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtEmailIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtEmailIDFocusLost(evt);
            }
        });
        jtxtEmailID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtEmailIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtEmailIDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtEmailID, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnCancel, jbtnOK});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jtxtEmailID});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnCancel, jbtnOK});

        getRootPane().setDefaultButton(jbtnOK);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOKActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_jbtnOKActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_jbtnCancelActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jtxtEmailIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtEmailIDFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtEmailIDFocusGained

    private void jtxtEmailIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtEmailIDFocusLost
        emailPickList.setVisible(false);
    }//GEN-LAST:event_jtxtEmailIDFocusLost

    private void jtxtEmailIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmailIDKeyPressed
        emailPickList.setLocation(jtxtEmailID.getX() + jPanel1.getX(), jtxtEmailID.getY() + jPanel1.getY() + (jtxtEmailID.getHeight() * 2));
        emailPickList.pickListKeyPress(evt);
    }//GEN-LAST:event_jtxtEmailIDKeyPressed

    private void jtxtEmailIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmailIDKeyReleased
        try {
            emailPickList.setReturnComponent(new JTextField[]{jtxtEmailID});
            PreparedStatement pstLocal = DeskFrame.connMpAdmin.prepareStatement("SELECT email1 FROM acnt_mst WHERE email1 <> '' AND email1 LIKE '%"+ jtxtEmailID.getText().toUpperCase() +"%'");
            emailPickList.setValidation(DeskFrame.connMpAdmin.prepareStatement("SELECT email1 FROM acnt_mst WHERE email1 = ?"));
            emailPickList.setPreparedStatement(pstLocal);
            emailPickList.pickListKeyRelease(evt);
        } catch (Exception ex) {
            lb.printToLogFile("Exception at jtxtEmailIDKeyReleased in Email Select", ex);
        }
    }//GEN-LAST:event_jtxtEmailIDKeyReleased

    private void doClose(int retStatus) {
        if(retStatus == RET_OK) {
            if(!jtxtEmailID.getText().equalsIgnoreCase("")) {
                VoucherDisplay vd = new VoucherDisplay(ref_no, jtxtEmailID.getText(), mode, md);
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter Email ID", "Select Email", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnOK;
    private javax.swing.JTextField jtxtEmailID;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}