/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package support;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.ResultSet;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author @JD@
 */
public abstract class NavigationPanel extends javax.swing.JPanel {
    private boolean saveFlag = true;
    private String editMode = "";
    public boolean wholesale = false, tag = false;
    public ResultSet viewData = null;
    String Syspath = System.getProperty("user.dir");

    /**
     * Creates new form NavigationPanel
     */
    public NavigationPanel() {
        initComponents();
        setSaveFlag(saveFlag);
        registerShortcutKey();
        setIconToPanel();
    }

    private void setIconToPanel() {
        Syspath += File.separator + "Resources" + File.separator + "Images" + File.separator;
        jbtnNew.setIcon(new ImageIcon(Syspath + "add.png"));
        jbtnEdit.setIcon(new ImageIcon(Syspath + "edit.png"));
        jbtnSave.setIcon(new ImageIcon(Syspath + "save.png"));
        jbtnDelete.setIcon(new ImageIcon(Syspath + "delete.png"));
        jbtnPrint.setIcon(new ImageIcon(Syspath + "print.png"));
        jbtnClose.setIcon(new ImageIcon(Syspath + "close.png"));
        jbtnFirst.setIcon(new ImageIcon(Syspath + "first.png"));
        jbtnPrevious.setIcon(new ImageIcon(Syspath + "previous.png"));
        jbtnNext.setIcon(new ImageIcon(Syspath + "next.png"));
        jbtnLast.setIcon(new ImageIcon(Syspath + "last.png"));
        jbtnView.setIcon(new ImageIcon(Syspath + "view.png"));
    }

    abstract public void callNew();
    abstract public void callEdit();
    abstract public void callSave();
    abstract public void callDelete();
    abstract public void callView();
    abstract public void callFirst();
    abstract public void callPrevious();
    abstract public void callNext();
    abstract public void callLast();
    abstract public void callClose();
    abstract public void callPrint();
    abstract public void setComponentTextFromResultSet();
    abstract public void setComponentEnabledDisabled(boolean flag);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void navKeyPress(java.awt.event.KeyEvent evt) {
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
            JButton button = (JButton)evt.getSource();
            button.doClick();
        }
    }

    private void navButtonPress(java.awt.event.ActionEvent evt) {
        JButton button = (JButton)evt.getSource();
        if(button == jbtnNew) {
            callNew();
        } else if(button == jbtnEdit) {
            callEdit();
        } else if(button == jbtnSave) {
            callSave();
        } else if(button == jbtnDelete) {
            callDelete();
        } else if(button == jbtnView) {
            callView();
        } else if(button == jbtnFirst) {
            callFirst();
            jbtnLast.requestFocusInWindow();
        } else if(button == jbtnPrevious) {
            callPrevious();
            jbtnLast.requestFocusInWindow();
        } else if(button == jbtnNext) {
            callNext();
            jbtnLast.requestFocusInWindow();
        } else if(button == jbtnLast) {
            callLast();
            jbtnLast.requestFocusInWindow();
        } else if(button == jbtnPrint) {
            callPrint();
        } else if(button == jbtnClose) {
            callClose();
        }
    }

    private void setEnableComp(boolean flag) {
        jbtnNew.setEnabled(flag);
        jbtnEdit.setEnabled(flag);
        jbtnSave.setEnabled(!flag);
        jbtnDelete.setEnabled(flag);
        jbtnView.setEnabled(flag);
        jbtnFirst.setEnabled(flag);
        jbtnPrevious.setEnabled(flag);
        jbtnNext.setEnabled(flag);
        jbtnLast.setEnabled(flag);
    }

    public void setMessage(String message) {
        jlblMessage.setText(message +" ");
    }

    public void setMode(String mode) {
        editMode = mode;
    }

    public String getMode() {
        return editMode;
    }

    public boolean getSaveFlag() {
        return saveFlag;
    }

    public final void setSaveFlag(boolean flag) {
        saveFlag = flag;
        if(saveFlag) {
            jbtnClose.setText("CLOSE");
            jbtnClose.setIcon(new ImageIcon(Syspath + "close.png"));
        } else {
            jbtnClose.setText("CANCEL");
            jbtnClose.setIcon(new ImageIcon(Syspath + "cancel.png"));
        }
        setEnableComp(saveFlag);
    }

    public void setNewFocus() {
        jbtnNew.requestFocusInWindow();
    }

    public void setEditFocus() {
        jbtnEdit.requestFocusInWindow();
    }

    public void setSaveFocus() {
        jbtnSave.requestFocusInWindow();
    }

    public void setDeleteFocus() {
        jbtnDelete.requestFocusInWindow();
    }

    public void setViewFocus() {
        jbtnView.requestFocusInWindow();
    }

    public void setFirstFocus() {
        jbtnFirst.requestFocusInWindow();
    }

    public void setPreviousFocus() {
        jbtnPrevious.requestFocusInWindow();
    }

    public void setNextFocus() {
        jbtnNext.requestFocusInWindow();
    }

    public void setLastFocus() {
        jbtnLast.requestFocusInWindow();
    }

    public void setCloseFocus() {
        jbtnClose.requestFocusInWindow();
    }

    private void registerShortcutKey() {
        KeyStroke newKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_N, KeyEvent.CTRL_MASK, false);
        Action newKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnNew.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(newKeyStroke, "New");
        this.getActionMap().put("New", newKeyAction);

        KeyStroke editKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_E, KeyEvent.CTRL_MASK, false);
        Action editKeyAction = new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnEdit.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(editKeyStroke, "Edit");
        this.getActionMap().put("Edit", editKeyAction);

        KeyStroke saveKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_S, KeyEvent.CTRL_MASK, false);
        Action saveKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnSave.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(saveKeyStroke, "Save");
        this.getActionMap().put("Save", saveKeyAction);

        KeyStroke delKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_D, KeyEvent.CTRL_MASK, false);
        Action delKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnDelete.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(delKeyStroke, "Delete");
        this.getActionMap().put("Delete", delKeyAction);

        KeyStroke viewKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_V, KeyEvent.ALT_MASK, false);
        Action viewKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnView.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(viewKeyStroke, "View");
        this.getActionMap().put("View", viewKeyAction);

        KeyStroke firstKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_HOME, 0, false);
        Action firstKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnFirst.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(firstKeyStroke, "First");
        this.getActionMap().put("First", firstKeyAction);

        KeyStroke prevKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_PAGE_UP, 0, false);
        Action prevKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnPrevious.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(prevKeyStroke, "Previous");
        this.getActionMap().put("Previous", prevKeyAction);

        KeyStroke nextKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_PAGE_DOWN, 0, false);
        Action nextKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnNext.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(nextKeyStroke, "Next");
        this.getActionMap().put("Next", nextKeyAction);

        KeyStroke lastKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_END, 0, false);
        Action lastKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnLast.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(lastKeyStroke, "Last");
        this.getActionMap().put("Last", lastKeyAction);

        KeyStroke closeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action closeKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(!PickList.isVisible)
                jbtnClose.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(closeKeyStroke, "Close");
        this.getActionMap().put("Close", closeKeyAction);

        KeyStroke printKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_P, KeyEvent.CTRL_MASK, false);
        Action printKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnPrint.doClick();
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(printKeyStroke, "Print");
        this.getActionMap().put("Print", printKeyAction);
    }

    public void setNewEnable(boolean flag) {
        jbtnNew.setEnabled(flag);
    }

    public void setEditEnable(boolean flag) {
        jbtnEdit.setEnabled(flag);
    }

    public void setSaveEnable(boolean flag) {
        jbtnSave.setEnabled(flag);
    }

    public void setDeleteEnable(boolean flag) {
        jbtnDelete.setEnabled(flag);
    }

    public void setViewEnable(boolean flag) {
        jbtnView.setEnabled(flag);
    }

    public void setFirstEnable(boolean flag) {
        jbtnFirst.setEnabled(flag);
    }

    public void setPreviousEnable(boolean flag) {
        jbtnPrevious.setEnabled(flag);
    }

    public void setNextEnable(boolean flag) {
        jbtnNext.setEnabled(flag);
    }

    public void setLastEnable(boolean flag) {
        jbtnLast.setEnabled(flag);
    }

    public void setPrintEnable(boolean flag) {
        jbtnPrint.setEnabled(flag);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnNew = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnView = new javax.swing.JButton();
        jbtnFirst = new javax.swing.JButton();
        jbtnPrevious = new javax.swing.JButton();
        jbtnNext = new javax.swing.JButton();
        jbtnLast = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jlblMessage = new javax.swing.JLabel();
        jbtnPrint = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(690, 76));
        setMinimumSize(new java.awt.Dimension(690, 76));
        setPreferredSize(new java.awt.Dimension(690, 76));

        jPanel1.setBackground(new java.awt.Color(253, 243, 243));

        jbtnNew.setBackground(new java.awt.Color(204, 255, 204));
        jbtnNew.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnNew.setForeground(new java.awt.Color(235, 35, 35));
        jbtnNew.setMnemonic('N');
        jbtnNew.setText("NEW");
        jbtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewActionPerformed(evt);
            }
        });
        jbtnNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnNewKeyPressed(evt);
            }
        });

        jbtnEdit.setBackground(new java.awt.Color(204, 255, 204));
        jbtnEdit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnEdit.setForeground(new java.awt.Color(235, 35, 35));
        jbtnEdit.setMnemonic('E');
        jbtnEdit.setText("EDIT");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });
        jbtnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnEditKeyPressed(evt);
            }
        });

        jbtnSave.setBackground(new java.awt.Color(204, 255, 204));
        jbtnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnSave.setForeground(new java.awt.Color(235, 35, 35));
        jbtnSave.setMnemonic('S');
        jbtnSave.setText("SAVE");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        jbtnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnSaveKeyPressed(evt);
            }
        });

        jbtnDelete.setBackground(new java.awt.Color(204, 255, 204));
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnDelete.setForeground(new java.awt.Color(235, 35, 35));
        jbtnDelete.setMnemonic('D');
        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jbtnDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnDeleteKeyPressed(evt);
            }
        });

        jbtnView.setBackground(new java.awt.Color(204, 255, 204));
        jbtnView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnView.setForeground(new java.awt.Color(235, 35, 35));
        jbtnView.setMnemonic('V');
        jbtnView.setText("VIEW");
        jbtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewActionPerformed(evt);
            }
        });
        jbtnView.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnViewKeyPressed(evt);
            }
        });

        jbtnFirst.setBackground(new java.awt.Color(204, 255, 204));
        jbtnFirst.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnFirst.setForeground(new java.awt.Color(235, 35, 35));
        jbtnFirst.setMnemonic('F');
        jbtnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFirstActionPerformed(evt);
            }
        });
        jbtnFirst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnFirstKeyPressed(evt);
            }
        });

        jbtnPrevious.setBackground(new java.awt.Color(204, 255, 204));
        jbtnPrevious.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnPrevious.setForeground(new java.awt.Color(235, 35, 35));
        jbtnPrevious.setMnemonic('P');
        jbtnPrevious.setMaximumSize(new java.awt.Dimension(45, 23));
        jbtnPrevious.setMinimumSize(new java.awt.Dimension(45, 23));
        jbtnPrevious.setPreferredSize(new java.awt.Dimension(45, 23));
        jbtnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreviousActionPerformed(evt);
            }
        });
        jbtnPrevious.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnPreviousKeyPressed(evt);
            }
        });

        jbtnNext.setBackground(new java.awt.Color(204, 255, 204));
        jbtnNext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnNext.setForeground(new java.awt.Color(235, 35, 35));
        jbtnNext.setMnemonic('X');
        jbtnNext.setMaximumSize(new java.awt.Dimension(45, 23));
        jbtnNext.setMinimumSize(new java.awt.Dimension(45, 23));
        jbtnNext.setPreferredSize(new java.awt.Dimension(45, 23));
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });
        jbtnNext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnNextKeyPressed(evt);
            }
        });

        jbtnLast.setBackground(new java.awt.Color(204, 255, 204));
        jbtnLast.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnLast.setForeground(new java.awt.Color(235, 35, 35));
        jbtnLast.setMnemonic('L');
        jbtnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLastActionPerformed(evt);
            }
        });
        jbtnLast.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnLastKeyPressed(evt);
            }
        });

        jbtnClose.setBackground(new java.awt.Color(204, 255, 204));
        jbtnClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnClose.setForeground(new java.awt.Color(235, 35, 35));
        jbtnClose.setMnemonic('C');
        jbtnClose.setText("CLOSE");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });
        jbtnClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnCloseKeyPressed(evt);
            }
        });

        jlblMessage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlblMessage.setForeground(new java.awt.Color(255, 51, 51));
        jlblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMessage.setText("     ");
        jlblMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtnPrint.setBackground(new java.awt.Color(204, 255, 204));
        jbtnPrint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnPrint.setForeground(new java.awt.Color(235, 35, 35));
        jbtnPrint.setMnemonic('P');
        jbtnPrint.setText("PRINT");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jbtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnPrintKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnClose, jbtnDelete, jbtnEdit, jbtnFirst, jbtnLast, jbtnNew, jbtnNext, jbtnPrevious, jbtnPrint, jbtnSave, jbtnView});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jlblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSave)
                    .addComponent(jbtnDelete)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnClose)
                        .addComponent(jbtnPrint))
                    .addComponent(jbtnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnView))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnClose, jbtnDelete, jbtnEdit, jbtnFirst, jbtnLast, jbtnNew, jbtnNext, jbtnPrevious, jbtnPrint, jbtnSave, jbtnView});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnNewActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnViewActionPerformed

    private void jbtnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFirstActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnFirstActionPerformed

    private void jbtnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreviousActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnPreviousActionPerformed

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnNextActionPerformed

    private void jbtnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLastActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnLastActionPerformed

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jbtnNewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnNewKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnNewKeyPressed

    private void jbtnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnEditKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnEditKeyPressed

    private void jbtnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnSaveKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnSaveKeyPressed

    private void jbtnDeleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnDeleteKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnDeleteKeyPressed

    private void jbtnViewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnViewKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnViewKeyPressed

    private void jbtnFirstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnFirstKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnFirstKeyPressed

    private void jbtnPreviousKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnPreviousKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnPreviousKeyPressed

    private void jbtnNextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnNextKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnNextKeyPressed

    private void jbtnLastKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnLastKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnLastKeyPressed

    private void jbtnCloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnCloseKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnCloseKeyPressed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        navButtonPress(evt);
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnPrintKeyPressed
        navKeyPress(evt);
    }//GEN-LAST:event_jbtnPrintKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnFirst;
    private javax.swing.JButton jbtnLast;
    private javax.swing.JButton jbtnNew;
    private javax.swing.JButton jbtnNext;
    private javax.swing.JButton jbtnPrevious;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnView;
    private javax.swing.JLabel jlblMessage;
    // End of variables declaration//GEN-END:variables
}